<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'badge_id' => 'HRD001',
                'kata_sandi' => Hash::make('password123'),
                'is_active' => true,
                'role' => 'HRD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'badge_id' => 'MIS001',
                'kata_sandi' => Hash::make('password123'),
                'is_active' => true,
                'role' => 'MIS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'badge_id' => 'HOD001',
                'kata_sandi' => Hash::make('password123'),
                'is_active' => true,
                'role' => 'HOD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'badge_id' => 'KRY001',
                'kata_sandi' => Hash::make('password123'),
                'is_active' => true,
                'role' => 'Karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('depart')->insert([
            [
                'code_depart' => 'IT',
                'nama' => 'Information Technology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code_depart' => 'HRD',
                'nama' => 'Human Resources Department',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code_depart' => 'PROD',
                'nama' => 'Production',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('karyawan')->insert([
            [
                'users_id' => 4,
                'depart_id' => 1,
                'nama' => 'Eka Fitri Anisa',
                'jabatan' => 'UI/UX Designer',
                'no_hp' => '081234567890',
                'tanggal_mulai' => '2024-01-01',
                'tanggal_selesai' => null,
                'active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('kategori_aset')->insert([
            [
                'nama' => 'Facilities',
                'managed_role' => 'HRD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Physical',
                'managed_role' => 'HOD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Credential',
                'managed_role' => 'MIS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('aset')->insert([
            [
                'kategori_id' => 1,
                'depart_id' => 2,
                'nama' => 'BPJS Kesehatan',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Fasilitas kesehatan karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'depart_id' => 2,
                'nama' => 'BPJS Ketenagakerjaan',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Fasilitas ketenagakerjaan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'depart_id' => 2,
                'nama' => 'Asuransi Karyawan',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Fasilitas asuransi karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'depart_id' => 2,
                'nama' => 'Transportasi Karyawan',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Fasilitas transportasi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'depart_id' => 2,
                'nama' => 'Seragam Kerja',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Seragam kerja karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Laptop Lenovo ThinkPad',
                'status' => 'active',
                'asset_no' => 'LAP-IT-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Laptop kerja karyawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Monitor Dell 24 Inch',
                'status' => 'active',
                'asset_no' => 'MON-IT-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Monitor kerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Keyboard Logitech',
                'status' => 'active',
                'asset_no' => 'KEY-IT-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Perangkat kerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Mouse Logitech',
                'status' => 'active',
                'asset_no' => 'MOU-IT-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Perangkat kerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Headset Logitech',
                'status' => 'active',
                'asset_no' => 'HST-IT-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Perangkat kerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Email Perusahaan',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'eka.fitri',
                'platform' => 'Microsoft Outlook',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Akun email perusahaan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'VPN',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'eka.fitri',
                'platform' => 'VPN',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Akses VPN perusahaan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Odoo',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'eka.fitri',
                'platform' => 'Odoo',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Akun sistem Odoo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Lumina',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'eka.fitri',
                'platform' => 'Lumina',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Akses sistem Lumina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'MySatnusa',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'eka.fitri',
                'platform' => 'MySatnusa',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Akses aplikasi internal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('assign_aset')->insert([
            [
                'karyawan_id' => 1,
                'aset_id' => 6,
                'tanggal_assign' => now()->toDateString(),
                'keterangan' => 'Laptop diberikan untuk kebutuhan pekerjaan',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('clearance')->insert([
            [
                'karyawan_id' => 1,
                'depart_id' => 1,
                'jenis' => 'resign',
                'tanggal_efektif' => now()->addDays(30)->toDateString(),
                'depart_tujuan_id' => null,
                'alasan' => 'Pengunduran diri dari perusahaan',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('clearance_approval')->insert([
            [
                'clearance_id' => 1,
                'step_order' => 1,
                'approved_by' => 3,
                'status' => 'pending',
                'notes' => null,
                'approved_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('clearance_aset')->insert([
            [
                'clearance_id' => 1,
                'aset_id' => 6,
                'status_pengembalian' => 'pending',
                'catatan' => 'Menunggu pengembalian laptop',
                'bukti_file' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}