<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'badge_id' => 'HRD001',
                'kata_sandi' => Hash::make('123123'),
                'is_active' => 1,
                'role' => 'HRD',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 00:42:02',
            ],
            [
                'id' => 2,
                'badge_id' => 'MIS001',
                'kata_sandi' => Hash::make('123123'),
                'is_active' => 1,
                'role' => 'MIS',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-13 03:40:37',
            ],
            [
                'id' => 3,
                'badge_id' => 'HOD001',
                'kata_sandi' => Hash::make('123123'),
                'is_active' => 1,
                'role' => 'HOD',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-13 03:40:37',
            ],
            [
                'id' => 4,
                'badge_id' => 'KRY001',
                'kata_sandi' => Hash::make('123123'),
                'is_active' => 1,
                'role' => 'Karyawan',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-24 17:08:29',
            ],
            [
                'id' => 5,
                'badge_id' => 'KRY002',
                'kata_sandi' => Hash::make('123123'),
                'is_active' => 1,
                'role' => 'Karyawan',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-14 02:46:17',
            ],
            [
                'id' => 6,
                'badge_id' => 'KRY003',
                'kata_sandi' => Hash::make('123123'),
                'is_active' => 1,
                'role' => 'Karyawan',
                'created_at' => '2026-07-02 08:00:46',
                'updated_at' => '2026-07-02 08:00:46',
            ],
        ]);

        DB::table('depart')->insert([
            [
                'id' => 1,
                'code_depart' => 'HRD',
                'nama' => 'Human Resource Development',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 2,
                'code_depart' => 'MIS',
                'nama' => 'Management Information System',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 3,
                'code_depart' => 'SDU',
                'nama' => 'Sales Development Unit',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 4,
                'code_depart' => 'FIN',
                'nama' => 'Finance & Accounting',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 5,
                'code_depart' => 'OPS',
                'nama' => 'Operational Support',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
        ]);

        DB::table('karyawan')->insert([
            [
                'id' => 1,
                'users_id' => 1,
                'depart_id' => 1,
                'nama' => 'Sarah Wijaya',
                'jabatan' => 'HR Manager',
                'no_hp' => '081211111111',
                'tanggal_mulai' => '2024-01-10',
                'tanggal_selesai' => null,
                'active' => 1,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-16 05:03:05',
            ],
            [
                'id' => 2,
                'users_id' => 2,
                'depart_id' => 1,
                'nama' => 'Kevin Adrian',
                'jabatan' => 'IT Infrastructure',
                'no_hp' => '081222222222',
                'tanggal_mulai' => '2024-01-15',
                'tanggal_selesai' => null,
                'active' => 1,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-17 04:36:33',
            ],
            [
                'id' => 3,
                'users_id' => 3,
                'depart_id' => 1,
                'nama' => 'Michael Tan',
                'jabatan' => 'Head Of Department',
                'no_hp' => '081233333333',
                'tanggal_mulai' => '2024-02-01',
                'tanggal_selesai' => null,
                'active' => 1,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-16 05:53:13',
            ],
            [
                'id' => 4,
                'users_id' => 4,
                'depart_id' => 1,
                'nama' => 'Rafael Pratama',
                'jabatan' => 'Sales Executive',
                'no_hp' => '081244444444',
                'tanggal_mulai' => '2024-03-01',
                'tanggal_selesai' => null,
                'active' => 1,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-24 17:08:29',
            ],
            [
                'id' => 5,
                'users_id' => 5,
                'depart_id' => 1,
                'nama' => 'Dinda Maharani',
                'jabatan' => 'Finance Staff',
                'no_hp' => '081255555555',
                'tanggal_mulai' => '2024-03-10',
                'tanggal_selesai' => null,
                'active' => 1,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-02 07:21:58',
            ],
        ]);

        DB::table('kategori_aset')->insert([
            [
                'id' => 1,
                'nama' => 'Aset Fisik',
                'managed_role' => 'HOD',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 2,
                'nama' => 'Aset Kredensial',
                'managed_role' => 'MIS',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 3,
                'nama' => 'Aset Fasilitas',
                'managed_role' => 'HRD',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
        ]);

        DB::table('aset')->insert([
            [
                'id' => 1,
                'kategori_id' => 1,
                'depart_id' => 1,
                'nama' => 'Laptop Lenovo ThinkPad',
                'status' => 'active',
                'asset_no' => 'LTP-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Laptop sales',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:14:09',
            ],
            [
                'id' => 2,
                'kategori_id' => 1,
                'depart_id' => 1,
                'nama' => 'iPhone 15 Pro',
                'status' => 'active',
                'asset_no' => 'IPH-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => 'Handphone sales',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:14:13',
            ],
            [
                'id' => 3,
                'kategori_id' => 1,
                'depart_id' => 1,
                'nama' => 'Printer Epson L3250',
                'status' => 'active',
                'asset_no' => 'PRN-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 4,
                'kategori_id' => 1,
                'depart_id' => 1,
                'nama' => 'HT Motorola',
                'status' => 'active',
                'asset_no' => 'HT-001',
                'jumlah' => 3,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 5,
                'kategori_id' => 1,
                'depart_id' => 1,
                'nama' => 'Mikrotik RB750',
                'status' => 'active',
                'asset_no' => 'NET-001',
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 6,
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Email Perusahaan',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'rafael@sdu.com',
                'platform' => 'Google Workspace',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 7,
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'VPN Kantor',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'vpn_rafael',
                'platform' => 'FortiClient',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 8,
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'GitLab Internal',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'kevin.dev',
                'platform' => 'GitLab',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 9,
                'kategori_id' => 2,
                'depart_id' => 1,
                'nama' => 'Microsoft 365',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'dinda.fin',
                'platform' => 'Microsoft',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-10 20:15:03',
            ],
            [
                'id' => 10,
                'kategori_id' => 2,
                'depart_id' => 2,
                'nama' => 'Attendance App',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => null,
                'username' => 'staff.ops',
                'platform' => 'Talenta',
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 11,
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Mobil Operasional HRD',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => 'BP 1234 HR',
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 12,
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Mess Karyawan Batam',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => 4,
                'username' => null,
                'platform' => null,
                'alamat' => 'Batam Center',
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 13,
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Kartu Akses Gedung',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => null,
                'cc_last4' => '7788',
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 14,
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Parkir VIP',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => 'Gedung A Lt.1',
                'no_plat' => null,
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 15,
                'kategori_id' => 3,
                'depart_id' => 1,
                'nama' => 'Motor Operasional',
                'status' => 'active',
                'asset_no' => null,
                'jumlah' => 1,
                'username' => null,
                'platform' => null,
                'alamat' => null,
                'no_plat' => 'BP 9981 ZZ',
                'cc_last4' => null,
                'catatan' => null,
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
        ]);

        DB::table('assign_aset')->insert([
            [
                'id' => 1,
                'karyawan_id' => 4,
                'aset_id' => 1,
                'tanggal_assign' => '2026-03-01',
                'keterangan' => 'Laptop operasional sales',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-24 16:52:12',
            ],
            [
                'id' => 2,
                'karyawan_id' => 4,
                'aset_id' => 2,
                'tanggal_assign' => '2026-03-01',
                'keterangan' => 'Handphone operasional sales',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-24 16:52:12',
            ],
            [
                'id' => 3,
                'karyawan_id' => 4,
                'aset_id' => 6,
                'tanggal_assign' => '2026-03-01',
                'keterangan' => 'Email perusahaan Rafael',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-24 16:52:12',
            ],
            [
                'id' => 4,
                'karyawan_id' => 4,
                'aset_id' => 7,
                'tanggal_assign' => '2026-03-01',
                'keterangan' => 'VPN kantor Rafael',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-07-24 16:52:12',
            ],
            [
                'id' => 5,
                'karyawan_id' => 5,
                'aset_id' => 3,
                'tanggal_assign' => '2026-03-10',
                'keterangan' => 'Printer finance',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-13 23:16:35',
            ],
            [
                'id' => 6,
                'karyawan_id' => 5,
                'aset_id' => 9,
                'tanggal_assign' => '2026-03-10',
                'keterangan' => 'Microsoft 365 finance',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-13 23:16:35',
            ],
            [
                'id' => 7,
                'karyawan_id' => 3,
                'aset_id' => 4,
                'tanggal_assign' => '2026-02-15',
                'keterangan' => 'HT operasional lapangan',
                'status' => 'aktif',
                'created_at' => '2026-05-09 16:13:19',
                'updated_at' => '2026-05-09 16:13:19',
            ],
            [
                'id' => 8,
                'karyawan_id' => 5,
                'aset_id' => 15,
                'tanggal_assign' => '2026-05-10',
                'keterangan' => 'apaaaa',
                'status' => 'aktif',
                'created_at' => '2026-05-10 05:34:50',
                'updated_at' => '2026-05-13 23:16:35',
            ],
            [
                'id' => 9,
                'karyawan_id' => 4,
                'aset_id' => 14,
                'tanggal_assign' => '2026-06-16',
                'keterangan' => null,
                'status' => 'aktif',
                'created_at' => null,
                'updated_at' => '2026-07-24 16:52:12',
            ],
        ]);
    }
}